namespace Ink.Entities;

public enum EntityMetaType
{
    UInt8,
    VarInt,
    VarLong,
    Single,
    String,
    Text,
    OptionalText,
    Slot,
    Bool,
    Rotations,
    BlockPosition,
    OptionalBlockPosition,
    Direction,
    OptionalUuid,
    BlockState,
    OptionalBlockState,
    Nbt,
    Particle,
    Particles,
    VillagerData,
    OptionalVarInt,
    Pose,
    CatVariant,
    WolfVariant,
    FrogVariant,
    OptionalGlobalPosition,
    PaintingVariant,
    SnifferState,
    ArmadilloState,
    Vector3,
    Quaternion
}
