namespace Ink.World;

public enum WorldEvent
{
    DispenserDispenses = 1000,
    DispenserFailsToDispense,
    DispenserShoots,
    EnderEyeLaunched,
    FireworkShot,
    IronDoorOpened,
    WoodenDoorOpened,
    WoodenTrapdoorOpened,
    FenceGateOpened,
    FireExtinguished,
    PlayRecord,
    IronDoorClosed,
    WoodenDoorClosed,
    WoodenTrapdoorClosed,
    FenceGateClosed,
    GhastWarns,
    GhastShoots,
    EnderdragonShoots,
    BlazeShoots,
    ZombieAttacksWoodDoor,
    ZombieAttacksIronDoor,
    ZombieBreaksWoodDoor,
    WitherBreaksBlock,
    WitherSpawned,
    WitherShoots,
    BatTakesOff,
    ZombieInfects,
    ZombieVillagerConverted,
    EnderDragonDeath,
    AnvilDestroyed,
    AnvilUsed,
    AnvilLanded,
    PortalTravel,
    ChorusFlowerGrown,
    ChorusFlowerDied,
    BrewingStandBrewed,
    IronTrapdoorOpened,
    IronTrapdoorClosed,
    EndPortalCreatedInOverworld,
    PhantomBites,
    ZombieConvertsToDrowned,
    HuskConvertsToZombieByDrowning,
    GrindstoneUsed,
    BookPageTurned,

    ComposterComposts = 1500,
    LavaConvertsBlock,
    RedstoneTorchBurnsOut,
    EnderEyePlaced,

    SpawnSmoke = 2000,
    BlockBreak,
    SplashPotion,
    EyeOfEnderEntityBreak,
    MobSpawnParticleEffect,
    BonemealParticles,
    DragonBreath,
    InstantSplashPotion,
    EnderDragonDestroysBlock,
    WetSpongeVaporizesInNether,

    EndGatewaySpawn = 3000,
    EnderDragonGrowl,
    ElectricSpark,
    CopperApplyWax,
    CopperRemoveWax,
    CopperScrapeOxidation,
}
